### ISSUE TITLE
Are there any installation instructions?

### ISSUE THREAD

**Issue by zarfld** [h3ndrk/qlcplus-mqtt#1]
are there any preconditions to use qlcplus with mqtt? i wonder where i can configure connection to my MQTTserver, or  how to install

**Comment by h3ndrk** [comment]
Hi @zarfld, I'm sorry but this repository is unmaintained, sadly.

Current status is: WebSocket protocol is implemented as stated in `README.md`. First MQTT tests are in `main.go` but *not* implemented as stated in `README.md`. Feel free to contribute!

(The Golang package paths need to be updated because I changed my GitHub username.)

For this reasons, there are no installation instructions.

I don't fully remember why I lost interest in this project, maybe I managed to control my lamps directly with Art-Net and not via QLC+. But if you are intending to use QLC+, the concept might still be relevant.

Hope this helps... :wink:

**Comment by zarfld** [comment]
Thanks for response! Now its clear for me
